#! /usr/bin/env python3
# Author: Martin C. Frith 2025

"""Make a tandemly-repeated version of a HMMER profile.

If the profile has nodes 0, 1, 2, ..., M, the output will have:
node 0, then nodes 1 to M-1 repeated however many times, then node M.
"""

import argparse
import gzip
import sys

def openFile(fileName):
    if fileName == "-":
        return sys.stdin
    if fileName.endswith(".gz"):
        return gzip.open(fileName, "rt")
    return open(fileName)

def main(args):
    leng = "0"
    hmmLines = []
    for line in openFile(args.filename):
        w = line.split()
        if w[0] == "NAME":
            line = line.rstrip() + "_x" + str(args.repeats) + "\n"
        if w[0] == "LENG":
            leng = w[1]
            line = w[0] + "  " + str((int(leng) - 1) * args.repeats + 1) + "\n"
        if w[0] == leng:
            for i in range(args.repeats - 1):
                for j in hmmLines:
                    print(j, end="")
        if w[0] == "1" or hmmLines:
            hmmLines.append(line)
        print(line, end="")

if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("filename", help="HMMER profile file")
    ap.add_argument("repeats", type=int, help="number of repeats")
    args = ap.parse_args()
    if args.repeats < 1:
        ap.error("argument repeats: must be > 0")
    main(args)
